# Generated by Django 5.1.3 on 2026-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collcover',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piececover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
