# Generated by Django 5.1.3 on 2026-01-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_collection_collcover_alter_piece_piececover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collcover',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piececover',
            field=models.CharField(max_length=1000),
        ),
    ]
