# Generated by Django 5.1.3 on 2026-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_collection_collcover_alter_piece_piececover'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='artist_photo',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
